name: AnvilPlus
version: maven-version-number
main: io.eliotesta98.AnvilPlus.Core.Main
api-version: 1.13
authors: [eliotesta98, xSavior_of_God]
softdepend: []

libraries:
  - com.googlecode.json-simple:json-simple:1.1.1
  - com.h2database:h2:2.1.212

legacy-libraries:
  - com.googlecode.json-simple:json-simple:1.1.1
  - com.h2database:h2:2.1.212

depend: []
commands:
  anvilplus:
    aliases: [ap]
permissions:
  ap.command.help:
    description: /ap <help>
    default: op
  ap.command.reload:
    description: /ap <reload>
    default: op