name: CustomGuiForAnvil
version: maven-version-number
main: io.eliotesta98.CustomGuiForAnvil.Core.Main
api-version: 1.13
authors: [eliotesta98, xSavior_of_God]
softdepend: []

libraries:
  - com.googlecode.json-simple:json-simple:1.1.1
  - com.h2database:h2:2.1.212

legacy-libraries:
  - com.googlecode.json-simple:json-simple:1.1.1
  - com.h2database:h2:2.1.212

depend: []
commands:
  cgfa:
    aliases: [customguiforanvil]
permissions:
  cgfa.command.help:
    description: /cgfa <help>
    default: op
  cgfa.command.reload:
    description: /cgfa <reload>
    default: op