name: CustomAnvilGUI
version: maven-version-number
main: io.eliotesta98.CustomAnvilGUI.Core.Main
api-version: 1.13
authors: [eliotesta98, xSavior_of_God]
softdepend: []
depend: []
commands:
  customanvilgui:
    aliases: [cagui]
permissions:
  cagui.command.help:
    description: /cagui <help>
    default: op
  cagui.command.reload:
    description: /cagui <reload>
    default: op